import jsPDF from "jspdf";

export const generatePayslip = (
  employeeName,
  salaryData
) => {

  const doc = new jsPDF();

  // TITLE

  doc.setFontSize(22);

  doc.text("Salary Payslip", 70, 20);

  // EMPLOYEE

  doc.setFontSize(16);

  doc.text(
    `Employee: ${employeeName}`,
    20,
    40
  );

  // LINE

  doc.line(20, 50, 190, 50);

  // SALARY DETAILS

  let y = 65;

  Object.entries(salaryData).forEach(
    ([key, value]) => {

      const label = key
        .replace(/([A-Z])/g, " $1")
        .replace(/^./, (str) => str.toUpperCase());

      doc.text(
        `${label}: Rs. ${Number(value).toLocaleString()}`,
        20,
        y
      );

      y += 12;
    }
  );

  // FINAL TITLE

  doc.setFontSize(18);

  doc.text(
    "Generated by Salary Calculator System",
    20,
    y + 20
  );

  // SAVE PDF

  doc.save(`${employeeName}-Payslip.pdf`);
};